//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_Datos_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Electrodomesticos
    {
        public Control_Electrodomesticos()
        {
            this.Control_Electrodomestico_Empleado = new HashSet<Control_Electrodomestico_Empleado>();
        }
    
        public int IdControl_Electrodomesticos { get; set; }
        public string Electrodomestico { get; set; }
    
        public virtual ICollection<Control_Electrodomestico_Empleado> Control_Electrodomestico_Empleado { get; set; }
    }
}
