//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_Datos_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public Documentos()
        {
            this.DocumentoxEmpleado = new HashSet<DocumentoxEmpleado>();
        }
    
        public int IDDocumento { get; set; }
        public string Tipo_Documento { get; set; }
    
        public virtual ICollection<DocumentoxEmpleado> DocumentoxEmpleado { get; set; }
    }
}
