//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_Datos_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Contrato = new HashSet<Contrato>();
            this.Control_Electrodomestico_Empleado = new HashSet<Control_Electrodomestico_Empleado>();
            this.DocumentoxEmpleado = new HashSet<DocumentoxEmpleado>();
            this.Empleado_Detalle = new HashSet<Empleado_Detalle>();
            this.Estudios = new HashSet<Estudios>();
            this.HabilidadEmpleado = new HashSet<HabilidadEmpleado>();
            this.MenuEmpleado = new HashSet<MenuEmpleado>();
            this.ServicioEmpleado = new HashSet<ServicioEmpleado>();
        }
    
        public int IDEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Ape_Pat { get; set; }
        public string Ape_Mat { get; set; }
        public string NombresCompletos { get; set; }
        public string Nro_Documento { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string E_mail { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Estado_Civil { get; set; }
        public string IdUbigeo { get; set; }
        public int IDTipoUsuario { get; set; }
        public int IDReligion { get; set; }
        public int IdDoc_Identidad { get; set; }
        public int IDIdioma { get; set; }
    
        public virtual ICollection<Contrato> Contrato { get; set; }
        public virtual ICollection<Control_Electrodomestico_Empleado> Control_Electrodomestico_Empleado { get; set; }
        public virtual Doc_Identidad Doc_Identidad { get; set; }
        public virtual ICollection<DocumentoxEmpleado> DocumentoxEmpleado { get; set; }
        public virtual ICollection<Empleado_Detalle> Empleado_Detalle { get; set; }
        public virtual ICollection<Estudios> Estudios { get; set; }
        public virtual Idiomas Idiomas { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        public virtual ICollection<HabilidadEmpleado> HabilidadEmpleado { get; set; }
        public virtual ICollection<MenuEmpleado> MenuEmpleado { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<ServicioEmpleado> ServicioEmpleado { get; set; }
    }
}
