//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_Datos_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilidades
    {
        public Habilidades()
        {
            this.HabilidadEmpleado = new HashSet<HabilidadEmpleado>();
        }
    
        public int IDHabilidad { get; set; }
        public string NombreHabilidad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<HabilidadEmpleado> HabilidadEmpleado { get; set; }
    }
}
