//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia_Datos_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuEmpleado
    {
        public int IDMenuEmpleado { get; set; }
        public int IDEmpleado { get; set; }
        public int IDMenu { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Menus Menus { get; set; }
    }
}
